INFO: plc_discovery version 0.4.0
INFO: macOS detected â€” using interface broadcast(s) for CIP: 169.254.255.255, 10.5.5.255
INFO: Discovering devices...
ERROR: Error broadcasting discover request
Traceback (most recent call last):
  File "/Users/albaraa/ald-control-system-phase-5/myenv/lib/python3.9/site-packages/pycomm3/cip_driver.py", line 247, in _broadcast_discover
    sock.sendto(message, (broadcast_address, 44818))
OSError: [Errno 49] Can't assign requested address
ERROR: Error broadcasting discover request
Traceback (most recent call last):
  File "/Users/albaraa/ald-control-system-phase-5/myenv/lib/python3.9/site-packages/pycomm3/cip_driver.py", line 247, in _broadcast_discover
    sock.sendto(message, (broadcast_address, 44818))
OSError: [Errno 49] Can't assign requested address
INFO: No Ethernet/IP devices discovered
INFO: Discovering devices...
ERROR: Error broadcasting discover request
Traceback (most recent call last):
  File "/Users/albaraa/ald-control-system-phase-5/myenv/lib/python3.9/site-packages/pycomm3/cip_driver.py", line 247, in _broadcast_discover
    sock.sendto(message, (broadcast_address, 44818))
OSError: [Errno 49] Can't assign requested address
ERROR: Error broadcasting discover request
Traceback (most recent call last):
  File "/Users/albaraa/ald-control-system-phase-5/myenv/lib/python3.9/site-packages/pycomm3/cip_driver.py", line 247, in _broadcast_discover
    sock.sendto(message, (broadcast_address, 44818))
OSError: [Errno 49] Can't assign requested address
ERROR: Error broadcasting discover request
Traceback (most recent call last):
  File "/Users/albaraa/ald-control-system-phase-5/myenv/lib/python3.9/site-packages/pycomm3/cip_driver.py", line 247, in _broadcast_discover
    sock.sendto(message, (broadcast_address, 44818))
OSError: [Errno 65] No route to host
ERROR: Error broadcasting discover request
Traceback (most recent call last):
  File "/Users/albaraa/ald-control-system-phase-5/myenv/lib/python3.9/site-packages/pycomm3/cip_driver.py", line 247, in _broadcast_discover
    sock.sendto(message, (broadcast_address, 44818))
OSError: [Errno 65] No route to host
ERROR: Error broadcasting discover request
Traceback (most recent call last):
  File "/Users/albaraa/ald-control-system-phase-5/myenv/lib/python3.9/site-packages/pycomm3/cip_driver.py", line 247, in _broadcast_discover
    sock.sendto(message, (broadcast_address, 44818))
OSError: [Errno 65] No route to host
ERROR: Error broadcasting discover request
Traceback (most recent call last):
  File "/Users/albaraa/ald-control-system-phase-5/myenv/lib/python3.9/site-packages/pycomm3/cip_driver.py", line 247, in _broadcast_discover
    sock.sendto(message, (broadcast_address, 44818))
OSError: [Errno 65] No route to host
INFO: No Ethernet/IP devices discovered
INFO: CIP discovered 0 device(s) (tried 169.254.255.255,10.5.5.255)
WARNING: PROFINET DCP on macOS has limitations (raw sockets/BPF). If discovery fails, run this on Linux/Windows or use CIP/Modbus/S7 alternatives.
WARNING: No --subnets provided; skipping Modbus/S7 sweeps
Wrote JSON results to .agent-workspace/TASK-20250920-163340-cdb7e0dd/quick_check_169.254.123.6.json

Discovered devices:
 protocol         ip              port   vendor/model/name
 ---------------- --------------- ------ ------------------------------
 modbus-tcp      169.254.123.6   502    

Notes / errors:
  cip: No CIP devices responded
  cip-unicast: 169.254.123.6: failed to open a connection
  profinet: pnio-dcp not available: Platform darwin is currently not supported.; profi-dcp not available: cannot import name 'DCP' from 'profi_dcp' (/Users/albaraa/ald-control-system-phase-5/myenv/lib/python3.9/site-packages/profi_dcp/__init__.py)

Raw JSON:
[
  {
    "protocol": "modbus-tcp",
    "ip": "169.254.123.6",
    "port": 502,
    "mac": null,
    "name": null,
    "vendor": null,
    "model": null,
    "extra": {
      "probe": "modbus-target"
    }
  }
]
